### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by limxdev**
Fixed Some GFX Errors (Strings too long)
Change Copay Strings to Byteball Strings

### CODE REVIEW

**Comment by limxdev** [comment]
Here a example about GFX 
https://dl.dropboxusercontent.com/u/21000833/Byteball/error.JPG
https://dl.dropboxusercontent.com/u/21000833/Byteball/error2.JPG

**Comment by tonyofbyteball** [comment]
Thanks, looks good but not sure about "Byteballers".  I think it should be cosigners.

**Comment by limxdev** [comment]
I have changed it to "Cosigners" I check it in the next version or update.

**Comment by tonyofbyteball** [comment]
It was more than once.  What's the German word for "cosigners"?

**Comment by tonyofbyteball** [comment]
Also, it is recommended to use unix newlines, otherwise diff shows like every line was changed.

**Comment by vakar8888** [comment]
cosigner in german: Bürge, Mitunterzeichner
to co-sign: bürgen, mitunterzeichnen

**Comment by limxdev** [comment]
Okay i add "Mitunterzeichner" That is possible. I hope the word isn't too long.

**Comment by tonyofbyteball** [comment]
There are still 3 instances of Byteballer and DOS newlines.

**Pull request closed without merging**
