### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by CorePrime95**
"Clear chat history" is now a button
bildschirmfoto_2017-06-25_13-07-09

Wallet home:
"Request specific amount" is now a button
The Byteball address has a larger font size, it is easier to read and to click

bildschirmfoto_2017-06-25_22-36-34

The links in the top navigation now have a slight hover effect, as it was not immediately clear that they are clickable from their looks
bildschirmfoto_2017-06-25_13-31-37

The button label "Generate QR code" now uses translation (no translations exist yet)
bildschirmfoto_2017-06-25_23-21-16

### CODE REVIEW

**Comment by tonyofbyteball** [comment]
translation - ok
hover - should be already evident enough as mouse pointer already changes when hovering, but doesn't hurt
buttons - not sure I like how it looks when we have two huge buttons in a row competing for attention, also the second is for a rarely used function

**Comment by CorePrime95** [comment]
Yeah, I understand. I think for "clear chat history" we have enough space and the previous link just looked like a placeholder. So I would leave it as a button or at least make it a centered link.

bildschirmfoto_2017-06-26_19-46-18

The "request a specific amount", I honestly didn't notice it existed at all because it was so small and light color. Its true I can't think of a situation in which I would use this function, you can use the invite for chat function and have more options in a chat.  I think it would be Ok to kick it out and bury it in some menu.

I would find the option to view your previously used addresses here more convenient, this is currently buried in a menu but more likely  to be used by people.

bildschirmfoto_2017-06-26_19-37-04

bildschirmfoto_2017-06-26_19-35-11

Or just keep it simple and only display the most important items Byteball address and "generate new address" on the screen.

bildschirmfoto_2017-06-26_19-40-43

**Comment by tonyofbyteball** [comment]
"clear chat history": centered link is ok but underline it to make obvious that it is a link
"request a specific amount": could be useful when meeting the payer in person (not a frequent occasion), yes it is better visible when the link is blue.  A link to the list of all addresses would be useful for pro users but two links don't look good.

**Comment by CorePrime95** [comment]
Ok, changes committed

bildschirmfoto_2017-06-27_19-21-27
bildschirmfoto_2017-06-27_19-21-16

**Pull request merged**
