### PR TITLE
Various UI improvements

### PR DESCRIPTION
**Pull request by CorePrime95**

### CODE REVIEW

**Comment by tonyofbyteball** [comment]
regarding text inputs can I see screenshots before merging?

**Comment by CorePrime95** [comment]
Sure, it was not easy to see the input line so I made it much darker. The text itself is slightly darker. 

grafik
pair2
pass

**Comment by tonyofbyteball** [comment]
Do you like how it looks now?  I'm not sure...

image

**Comment by CorePrime95** [comment]
Yeah, it looks strange in this screen because the input line and dropdown box touch and have different colors. But I find that a visible input line greatly improves usability in other screens. An option would be to make the dropdown box the same color. I'll play around.

**Comment by CorePrime95** [comment]
Ok, what about this: default input line color is lighter but still visible. On contract screens, input fields and boxes have a small space in between.

bildschirmfoto_2017-06-22_21-51-55
bildschirmfoto_2017-06-22_21-49-44
bildschirmfoto_2017-06-22_21-43-12

**Comment by tonyofbyteball** [comment]
Looks good!

**Pull request merged**
